version: "3.3"

services: 
    web:
        build: .
        ports: 
            - 8080:8080
        environment: 
            LOCAL: "true"
            PORT: 8080
            DATABASE_URL: host=localhost user=postgres password=12345 dbname=postgres port=5435 sslmode=disable
    # redis:
    #     image: redis:alpine